"""
CY4500-EPR / EZ-PD Protocol Analyzer Utility 4.2.0 protocol definitions.
Reverse-engineering snapshot: 2026-08-19.

v10 cumulative additions confirmed by direct CY4500-EPR capture and
Analyzer Utility 4.2.0 bytecode:
  * EP81 transfer terminator / idle short packet: AA AB AC AD
  * Data-bearing EP81 transfer: N*64-byte records + 4-byte terminator
  * USB-PD Extended Header Request Chunk bit: bit 10

Only values already established by bytecode analysis / physical tests are
treated as confirmed. Unknown semantics are explicitly marked.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# USB ------------------------------------------------------------------------

USB_VID_CYPRESS = 0x04B4
USB_PID_CY4500_LEGACY = 0x0078
USB_PID_ANALYZER_F67E = 0xF67E
USB_PID_CY4500_EPR = 0xFDEF
USB_SUPPORTED_PIDS = (
    USB_PID_CY4500_LEGACY,
    USB_PID_ANALYZER_F67E,
    USB_PID_CY4500_EPR,
)

USB_INTERFACE = 0

EP_CMD_OUT = 0x02
EP_PD_IN = 0x81
EP_SCOPE_IN = 0x83
EP_CMD_RESP_IN = 0x84

ENDPOINTS = {
    "CMD_OUT": EP_CMD_OUT,
    "PD_IN": EP_PD_IN,
    "SCOPE_IN": EP_SCOPE_IN,
    "CMD_RESP_IN": EP_CMD_RESP_IN,
}

MAX_PD_READ_SIZE = 65535
MAX_SCOPE_READ_SIZE = 13000
SHORT_PACKET_SIZE = 8

# Firmware commands ----------------------------------------------------------

CMD_TRIGGER = 0x02
CMD_STOP = 0x03
CMD_GET_VERSION = 0x04
CMD_TERMINATION = 0x07
CMD_START = 0x10
CMD_GET_VOLT_AMP = 0x11

# CMD_GET_VOLT_AMP (0x11) live-status response:
#   8 bytes total, interpreted as four little-endian uint16 words:
#     word0 = VBUS ADC raw
#     word1 = VBUS current ADC raw
#     word2 = CC1 ADC raw
#     word3 = CC2 ADC raw
#
# The formulas below are reconstructed directly from
# EZ-PD Protocol Analyzer Utility 4.2.0 VoltAmpUpdater bytecode.
#
# Default / legacy CY4500:
#   factor = 11
#   val    = 3296
#
# CY4500-EPR when DataManager.isEPR() and PID == 0xFDEF:
#   factor = 12
#   val    = 4048
#
# Conversion:
#   VBUS[mV] = raw0 * val * factor // 4096
#   IBUS[mA] = abs(raw1 - 2048) * 100 // 36
#   CC1 [mV] = raw2 * val // 4096
#   CC2 [mV] = raw3 * val // 4096
LIVE_STATUS_RESPONSE_SIZE = 8
LIVE_ADC_COUNTS = 4096
LIVE_CURRENT_ZERO_RAW = 2048
LIVE_CURRENT_NUMERATOR_MA = 100
LIVE_CURRENT_DENOMINATOR_COUNTS = 36

LIVE_LEGACY_VBUS_FACTOR = 11
LIVE_LEGACY_ADC_REF_MV = 3296

LIVE_FDEF_VBUS_FACTOR = 12
LIVE_FDEF_ADC_REF_MV = 4048

LIVE_CURRENT_DOC_TYPICAL_ACCURACY_A = 0.15

CMD_GET_DEVICE_TYPE = 0x12
CMD_CHECK_DEVICE = 0x13

COMMANDS = {
    "TRIGGER": CMD_TRIGGER,
    "STOP": CMD_STOP,
    "GET_VERSION": CMD_GET_VERSION,
    "TERMINATION": CMD_TERMINATION,
    "START": CMD_START,
    "GET_VOLT_AMP": CMD_GET_VOLT_AMP,
    "GET_DEVICE_TYPE": CMD_GET_DEVICE_TYPE,
    "CHECK_DEVICE": CMD_CHECK_DEVICE,
}

# Exact payloads generated by Analyzer Utility 4.2.0.
# The meaning of START's uint32 LE value 4 at bytes 4..7 is still unknown.
CMD_START_PAYLOAD = bytes.fromhex("10 00 00 00 04 00 00 00")
CMD_STOP_PAYLOAD = bytes.fromhex("03 00 00 00")

# Trigger --------------------------------------------------------------------

TRIGGER_PACKET_SIZE = 64
TRIGGER_OFFSET_CMD = 0
TRIGGER_OFFSET_START_SNO_ENABLE = 4
TRIGGER_OFFSET_END_SNO_ENABLE = 5
TRIGGER_OFFSET_SOP_ENABLE = 6
TRIGGER_OFFSET_MSG_TYPE_ENABLE = 7
TRIGGER_OFFSET_OBJ_COUNT_ENABLE = 8
TRIGGER_OFFSET_MSG_ID_ENABLE = 9
TRIGGER_OFFSET_MSG_TYPE = 10
TRIGGER_OFFSET_MSG_CLASS = 11
TRIGGER_OFFSET_SOP = 12
TRIGGER_OFFSET_OBJ_COUNT = 13
TRIGGER_OFFSET_MSG_ID = 14
TRIGGER_OFFSET_START_SNO = 16
TRIGGER_OFFSET_END_SNO = 20

TRIGGER_MSG_CLASS = {
    "CONTROL": 0,
    "DATA": 1,
    "EXTENDED": 2,
}
TRIGGER_MSG_CLASS_BY_VALUE = {v: k for k, v in TRIGGER_MSG_CLASS.items()}

TRIGGER_SOP_TYPE = {
    "SOP": 0,
    "SOP_PRIME": 1,
    "SOP_DPRIME": 2,
    "SOP_PRIME_DEBUG": 3,
    "SOP_DPRIME_DEBUG": 4,
    "HARD_RESET": 5,
    "CABLE_RESET": 6,
}
TRIGGER_SOP_TYPE_BY_VALUE = {v: k for k, v in TRIGGER_SOP_TYPE.items()}

# Message dictionaries -------------------------------------------------------

CONTROL_MSG_TYPES = (
    "C_RSVD0", "GOODCRC", "GOTO_MIN", "ACCEPT", "REJECT", "PING", "PS_RDY",
    "GET_SOURCE_CAP", "GET_SINK_CAP", "DR_SWAP", "PR_SWAP", "VCONN_SWAP",
    "WAIT", "SOFT_RESET", "DATA_RESET", "DATA_RESET_COMPLETE", "NOT_SUPPORTED",
    "GET_SOURCE_CAP_EXTENDED", "GET_STATUS", "FR_SWAP", "GET_PPS_STATUS",
    "GET_COUNTRY_CODES", "GET_SINK_CAP_EXTENDED", "GET_SOURCE_INFO",
    "GET_REVISION", "C_RSVD25", "C_RSVD26", "C_RSVD27", "C_RSVD28",
    "C_RSVD29", "C_RSVD30", "C_RSVD31",
)

DATA_MSG_TYPES = (
    "D_RSVD0", "SOURCE_CAPABILITIES", "REQUEST", "BIST", "SINK_CAPABILITIES",
    "BATTERY_STATUS", "ALERT", "GET_COUNTRY_INFO", "ENTER_USB", "EPR_REQUEST",
    "EPR_MODE", "SOURCE_INFO", "REVISION", "D_RSVD13", "D_RSVD14",
    "VENDOR_DEFINED", "D_RSVD16", "D_RSVD17", "D_RSVD18", "D_RSVD19",
    "D_RSVD20", "D_RSVD21", "D_RSVD22", "D_RSVD23", "D_RSVD24", "D_RSVD25",
    "D_RSVD26", "D_RSVD27", "D_RSVD28", "D_RSVD29", "D_RSVD30", "D_RSVD31",
)

EXTENDED_MSG_TYPES = (
    "E_RSVD0", "SOURCE_CAPABILITIES_EXTENDED", "STATUS", "GET_BATTERY_CAP",
    "GET_BATTERY_STATUS", "BATTERY_CAPABILITIES", "GET_MANUFACTURER_INFO",
    "MANUFACTURER_INFO", "SECURITY_REQUEST", "SECURITY_RESPONSE",
    "FIRMWARE_UPDATE_REQUEST", "FIRMWARE_UPDATE_RESPONSE", "PPS_STATUS",
    "COUNTRY_INFO", "COUNTRY_CODES", "SINK_CAPABILITIES_EXTENDED",
    "EXTENDED_CONTROL_MSG", "EPR_SOURCE_CAPABILITIES", "EPR_SINK_CAPABILITIES",
    "E_RSVD19", "E_RSVD20", "E_RSVD21", "E_RSVD22", "E_RSVD23", "E_RSVD24",
    "E_RSVD25", "E_RSVD26", "E_RSVD27", "E_RSVD28", "E_RSVD29", "E_RSVD30",
    "E_RSVD31",
)

MESSAGE_TYPES_BY_CLASS = {
    "CONTROL": CONTROL_MSG_TYPES,
    "DATA": DATA_MSG_TYPES,
    "EXTENDED": EXTENDED_MSG_TYPES,
}


# Semantic USB-PD detail decoders ---------------------------------------------
#
# Keep base Analyzer Utility message dictionaries above unchanged. These maps
# add detail without losing the original Message Type classification.

# Confirmed on the user's direct CY4500-EPR capture:
# EXTENDED_CONTROL_MSG payload type 3 appears periodically from Sink while in
# EPR, and type 4 is the paired Source response.
EXTENDED_CONTROL_TYPES = {
    3: "EPR_KEEPALIVE",
    4: "EPR_KEEPALIVE_ACK",
}

PDO_SUPPLY_TYPES = {
    0: "FIXED",
    1: "BATTERY",
    2: "VARIABLE",
    3: "AUGMENTED",
}

# USB-PD APDO subtype values relevant to current work.
# subtype 1 (AVS) is independently validated by the observed 0xD3C096F0:
# 15.0 V minimum, 48.0 V maximum, PDP 240 W.
# subtype 2 is labeled SPR_AVS, but its field layout is intentionally not
# decoded yet in this module because that encoding has not been independently
# frozen from the current Analyzer Utility bytecode / direct captures.
APDO_TYPES = {
    0: "PPS",
    1: "AVS",
    2: "SPR_AVS",
    3: "RSVD",
}

TIMESTAMP_UNIT = "us"

# CC termination -------------------------------------------------------------

TERM_RP = 1
TERM_RA = 2
TERM_RD = 3
TERM_NONE = 4

CC_TERMINATION = {
    "RP": TERM_RP,
    "RA": TERM_RA,
    "RD": TERM_RD,
    "NONE": TERM_NONE,
}
CC_TERMINATION_BY_VALUE = {v: k for k, v in CC_TERMINATION.items()}

TERMINATION_PACKET_SIZE = 12
TERMINATION_OFFSET_CMD = 0
TERMINATION_OFFSET_CC1 = 4
TERMINATION_OFFSET_CC2 = 8

# Capture transport ----------------------------------------------------------

CAPTURE_RECORD_SIZE = 64
CAPTURE_METADATA_SIZE = 20
CAPTURE_MESSAGE_AREA_SIZE = 44

# CONFIRMED by direct capture on CY4500-EPR:
#   idle transfer       = AA AB AC AD
#   data-bearing xfer   = N * 64-byte records + AA AB AC AD
#
# The 4-byte marker is delivered as a short bulk packet (EP max packet = 64),
# which terminates the host-side bulk read. Analyzer Utility naturally ignores
# it because readData() processes only len // 64 full records.
EP81_TRANSFER_TERMINATOR = bytes.fromhex("AA AB AC AD")

# Scope / Graph transport -----------------------------------------------------
#
# Analyzer Utility 4.2.0 ScopeCollecter confirms:
#   * EP83 payload is processed in 64-byte units.
#   * Each 64-byte unit contains five 12-byte samples at offsets
#     0, 12, 24, 36, 48.
#   * Bytes 60..63 are not parsed by ScopeCollecter.
#
# Direct FDEF firmware 3.0.0.3 capture further confirms bytes 60..63 are
# consistently 00 00 00 00 in the tested stream. Keep them as reserved/padding
# rather than assigning semantics.
SCOPE_PACKET_SIZE = 64
SCOPE_SAMPLES_PER_PACKET = 5
SCOPE_SAMPLE_SIZE = 12
SCOPE_SAMPLE_DATA_SIZE = SCOPE_SAMPLES_PER_PACKET * SCOPE_SAMPLE_SIZE
SCOPE_PADDING_OFFSET = SCOPE_SAMPLE_DATA_SIZE
SCOPE_PADDING_SIZE = SCOPE_PACKET_SIZE - SCOPE_SAMPLE_DATA_SIZE

SCOPE_OFFSET_TIMESTAMP = 0
SCOPE_OFFSET_VBUS = 4
SCOPE_OFFSET_CC1 = 6
SCOPE_OFFSET_CC2 = 8
SCOPE_OFFSET_IBUS = 10

# ScopeCollecter ignores timestamp 0 and 2913774506 decimal.
# 2913774506 == 0xADACABAA, i.e. wire bytes AA AB AC AD in little-endian.
SCOPE_TIMESTAMP_SKIP_MAGIC = 0xADACABAA

# Exact Analyzer Utility rollover quirk:
# on raw u32 timestamp wrap it adds 0xFFFFFFFF, not 0x100000000.
# This makes the accumulated time one microsecond short per wrap.
SCOPE_TIMESTAMP_WRAP_ADD_UTILITY = 0xFFFFFFFF

SCOPE_CSV_COLUMNS = (
    "Transfer", "Packet", "Sample", "Timestamp Raw", "Timestamp(us)",
    "Vbus Raw", "Vbus(mV)", "Vbus(V)",
    "CC1 Raw", "CC1(mV)", "CC1(V)",
    "CC2 Raw", "CC2(mV)", "CC2(V)",
    "Ibus Raw", "Ibus(mA)", "Ibus(A)", "Power(W)",
    "Padding",
)

CAPTURE_OFFSET_SNO = 0x00
CAPTURE_OFFSET_VBUS_RAW = 0x04
CAPTURE_OFFSET_START_TIME = 0x08
CAPTURE_OFFSET_END_TIME = 0x0C
CAPTURE_OFFSET_PACKET_WORD = 0x10
CAPTURE_OFFSET_MESSAGE = 0x14

CAPTURE_OFFSETS = {
    "SNO": CAPTURE_OFFSET_SNO,
    "VBUS_RAW": CAPTURE_OFFSET_VBUS_RAW,
    "START_TIME": CAPTURE_OFFSET_START_TIME,
    "END_TIME": CAPTURE_OFFSET_END_TIME,
    "PACKET_WORD": CAPTURE_OFFSET_PACKET_WORD,
    "MESSAGE": CAPTURE_OFFSET_MESSAGE,
}

NORMAL_PACKET_BASE_SIZE = CAPTURE_METADATA_SIZE
DATA_OBJECT_SIZE = 4

# 32-bit Analyzer packet word. Bits 15:0 are the USB-PD Message Header.
PACKET_WORD_FIELDS = {
    "MSG_TYPE": (0, 5),
    "DATA_ROLE": (5, 1),
    "SPEC_REV": (6, 2),
    "POWER_ROLE": (8, 1),
    "MSG_ID": (9, 3),
    "OBJ_COUNT": (12, 3),
    "EXTENDED": (15, 1),
    "SOP_TYPE": (16, 4),
    "CHUNK_NO": (20, 6),
    "PKT_TYPE": (26, 2),
    "IDLE_ERROR": (28, 1),
    "EOP_ERROR": (29, 1),
    "CRC_ERROR": (30, 1),
    "OK": (31, 1),
}

PKT_TYPE = {
    0: "PD_PKT",
    1: "VOLT_PKT",
    2: "RSVD2",
    3: "RSVD3",
}

CAPTURE_SOP_TYPE = {
    0: "SOP",
    1: "SOP_PRIME",
    2: "SOP_DPRIME",
    3: "SOP_P_DBG",
    4: "SOP_DP_DBG",
    5: "HARD_RESET",
    6: "CABLE_RESET",
    7: "INVALID",
}

SPEC_REV = {
    0: "v1",
    1: "v2",
    2: "v3",
    3: "RSVD",
}

# Extended Message -----------------------------------------------------------

EXTENDED_HEADER_SIZE = 2
EXTENDED_DATA_SIZE_MASK = 0x01FF
EXTENDED_CHUNK_NO_SHIFT = 11
EXTENDED_CHUNK_NO_MASK = 0x0F
EXTENDED_CHUNKED_BIT = 15
EXTENDED_BYTES_PER_RECORD = 44

# CONFIRMED by direct EPR_SOURCE_CAPABILITIES chunk exchange:
# bit 10 = Request Chunk.
# Example observed Extended Headers:
#   0x802C -> chunked=1, request_chunk=0, chunk_no=0, data_size=44
#   0x8C00 -> chunked=1, request_chunk=1, chunk_no=1, data_size=0
#   0x882C -> chunked=1, request_chunk=0, chunk_no=1, data_size=44
EXTENDED_REQUEST_CHUNK_BIT = 10

# VBUS -----------------------------------------------------------------------

# Confirmed Analyzer Utility integer arithmetic:
# FDEF/EPR: raw * 4048 * 12 / 4096
# other:    raw * 3296 * 11 / 4096
# Direct capture comparison confirms the EPR result is millivolt-scaled;
# vbus_epr_volts() converts it to volts.
VBUS_EPR_MULTIPLIER = 4048
VBUS_EPR_GAIN = 12
VBUS_EPR_DIVISOR = 4096

VBUS_LEGACY_MULTIPLIER = 3296
VBUS_LEGACY_GAIN = 11
VBUS_LEGACY_DIVISOR = 4096

# CSV ------------------------------------------------------------------------

CSV_COLUMNS = (
    "Sno", "Ok", "SOP", "Message", "Msg Id", "Data Role", "Power Role",
    "Obj Count", "Rev", "Duration", "Delta", "Vbus(V)", "Data",
    "Start Time", "End Time",
)

# Analyzer Utility 4.2.0 ExcelExportHandler writes getsTime() for BOTH
# Start Time and End Time, despite USBPacketData having a separate eTime.
ANALYZER_420_END_TIME_EXPORT_BUG = True

# Helpers --------------------------------------------------------------------

def get_bits(value: int, shift: int, width: int) -> int:
    if shift < 0 or width <= 0:
        raise ValueError("invalid bit field")
    return (int(value) >> shift) & ((1 << width) - 1)


def read_u16_le(data: bytes, offset: int = 0) -> int:
    end = offset + 2
    if offset < 0 or end > len(data):
        raise ValueError("uint16 read exceeds buffer")
    return int.from_bytes(data[offset:end], "little", signed=False)


def read_u32_le(data: bytes, offset: int = 0) -> int:
    end = offset + 4
    if offset < 0 or end > len(data):
        raise ValueError("uint32 read exceeds buffer")
    return int.from_bytes(data[offset:end], "little", signed=False)


def write_u32_le(value: int) -> bytes:
    value = int(value)
    if not 0 <= value <= 0xFFFFFFFF:
        raise ValueError("value must fit uint32")
    return value.to_bytes(4, "little", signed=False)


def decode_packet_word(word: int) -> dict[str, int]:
    word = int(word) & 0xFFFFFFFF
    return {
        name: get_bits(word, shift, width)
        for name, (shift, width) in PACKET_WORD_FIELDS.items()
    }


def get_message_class_from_fields(*, extended: int, obj_count: int) -> str:
    if int(extended):
        return "EXTENDED"
    if int(obj_count):
        return "DATA"
    return "CONTROL"


def get_message_class(word: int) -> str:
    fields = decode_packet_word(word)
    return get_message_class_from_fields(
        extended=fields["EXTENDED"],
        obj_count=fields["OBJ_COUNT"],
    )


def get_message_name(msg_class: str, msg_type: int, default: Optional[str] = None):
    key = str(msg_class).upper()
    table = MESSAGE_TYPES_BY_CLASS.get(key)
    if table is None:
        if default is not None:
            return default
        raise KeyError(f"unknown message class: {msg_class!r}")
    idx = int(msg_type)
    return table[idx] if 0 <= idx < len(table) else default


def get_message_name_from_word(word: int, default: Optional[str] = None):
    fields = decode_packet_word(word)
    cls = get_message_class_from_fields(
        extended=fields["EXTENDED"],
        obj_count=fields["OBJ_COUNT"],
    )
    return get_message_name(cls, fields["MSG_TYPE"], default)


def decode_extended_header(header: int) -> dict[str, int]:
    """Decode the USB-PD 16-bit Extended Message Header fields confirmed here."""
    header = int(header) & 0xFFFF
    return {
        "raw": header,
        "data_size": header & EXTENDED_DATA_SIZE_MASK,
        "request_chunk": (header >> EXTENDED_REQUEST_CHUNK_BIT) & 1,
        "chunk_no": (header >> EXTENDED_CHUNK_NO_SHIFT) & EXTENDED_CHUNK_NO_MASK,
        "chunked": (header >> EXTENDED_CHUNKED_BIT) & 1,
    }


def split_capture_transfer(data: bytes) -> list[bytes]:
    """
    Split one complete EP81 bulk transfer into its 64-byte capture records.

    Confirmed CY4500-EPR framing:
        idle transfer:
            AA AB AC AD

        data transfer:
            [64-byte record] * N + AA AB AC AD

    This function is intentionally strict. It preserves USB-transfer framing
    assumptions instead of silently concatenating malformed or partial reads.
    """
    data = bytes(data)

    if data == EP81_TRANSFER_TERMINATOR:
        return []

    if len(data) < len(EP81_TRANSFER_TERMINATOR):
        raise ValueError(
            f"EP81 transfer too short: {len(data)} bytes"
        )

    if not data.endswith(EP81_TRANSFER_TERMINATOR):
        raise ValueError(
            "EP81 transfer is missing AA AB AC AD terminator"
        )

    payload = data[:-len(EP81_TRANSFER_TERMINATOR)]

    if not payload:
        raise ValueError(
            "empty payload before EP81 terminator; expected idle marker only"
        )

    if len(payload) % CAPTURE_RECORD_SIZE:
        raise ValueError(
            f"EP81 payload is not {CAPTURE_RECORD_SIZE}-byte aligned: "
            f"{len(payload)} bytes"
        )

    return [
        payload[offset:offset + CAPTURE_RECORD_SIZE]
        for offset in range(0, len(payload), CAPTURE_RECORD_SIZE)
    ]


def normal_packet_effective_size(obj_count: int) -> int:
    n = int(obj_count)
    if not 0 <= n <= 7:
        raise ValueError("obj_count must be 0..7")
    return NORMAL_PACKET_BASE_SIZE + n * DATA_OBJECT_SIZE


def extended_record_count(data_size: int) -> int:
    n = int(data_size)
    if not 0 <= n <= 0x1FF:
        raise ValueError("Extended data_size must be 0..511")
    total = n + EXTENDED_HEADER_SIZE
    return (total + EXTENDED_BYTES_PER_RECORD - 1) // EXTENDED_BYTES_PER_RECORD


def vbus_epr_raw_scale(raw: int) -> int:
    raw = int(raw)
    if raw < 0:
        raise ValueError("raw must be >= 0")
    return raw * VBUS_EPR_MULTIPLIER * VBUS_EPR_GAIN // VBUS_EPR_DIVISOR


def vbus_legacy_raw_scale(raw: int) -> int:
    raw = int(raw)
    if raw < 0:
        raise ValueError("raw must be >= 0")
    return raw * VBUS_LEGACY_MULTIPLIER * VBUS_LEGACY_GAIN // VBUS_LEGACY_DIVISOR



def live_ibus_milliamps(raw1: int) -> int:
    """
    Analyzer Utility 4.2.0 live-current conversion.

        IBUS[mA] = abs(raw1 - 2048) * 100 // 36

    This intentionally reproduces the Utility's integer arithmetic.
    """
    raw1 = int(raw1)
    if not 0 <= raw1 <= 0xFFFF:
        raise ValueError("raw1 must fit uint16")

    return (
        abs(raw1 - LIVE_CURRENT_ZERO_RAW)
        * LIVE_CURRENT_NUMERATOR_MA
        // LIVE_CURRENT_DENOMINATOR_COUNTS
    )


def live_ibus_amps(raw1: int, *, clamp_display_zero: bool = False) -> float:
    """
    Return Analyzer Utility 4.2.0 live current in amperes.

    clamp_display_zero is retained for API compatibility with v6; the exact
    Utility formula is already non-negative because it uses abs().
    """
    current = live_ibus_milliamps(raw1) / 1000.0
    if clamp_display_zero and current < 0.0:
        return 0.0
    return current


def _live_voltage_params(*, is_epr: bool, product_id: int) -> tuple[int, int]:
    """
    Reproduce Analyzer Utility 4.2.0 factor/val selection.

    Only the EPR + PID 0xFDEF combination switches to factor=12,val=4048.
    All other cases use the legacy factor=11,val=3296 path.
    """
    if is_epr and int(product_id) == USB_PID_CY4500_EPR:
        return LIVE_FDEF_VBUS_FACTOR, LIVE_FDEF_ADC_REF_MV
    return LIVE_LEGACY_VBUS_FACTOR, LIVE_LEGACY_ADC_REF_MV


def decode_live_status_response(
    data: bytes,
    *,
    is_epr: bool = True,
    product_id: int = USB_PID_CY4500_EPR,
) -> dict[str, object]:
    """
    Decode the exact 8-byte CMD_GET_VOLT_AMP response using the Analyzer
    Utility 4.2.0 VoltAmpUpdater formulas.

    Layout:
      word0 = VBUS ADC raw
      word1 = IBUS ADC raw
      word2 = CC1 ADC raw
      word3 = CC2 ADC raw
    """
    data = bytes(data)
    if len(data) != LIVE_STATUS_RESPONSE_SIZE:
        raise ValueError(
            f"live status response must be exactly "
            f"{LIVE_STATUS_RESPONSE_SIZE} bytes, got {len(data)}"
        )

    raw0 = int.from_bytes(data[0:2], "little")
    raw1 = int.from_bytes(data[2:4], "little")
    raw2 = int.from_bytes(data[4:6], "little")
    raw3 = int.from_bytes(data[6:8], "little")

    factor, val_mv = _live_voltage_params(
        is_epr=is_epr,
        product_id=product_id,
    )

    vbus_mV = raw0 * val_mv * factor // LIVE_ADC_COUNTS
    ibus_mA = live_ibus_milliamps(raw1)
    cc1_mV = raw2 * val_mv // LIVE_ADC_COUNTS
    cc2_mV = raw3 * val_mv // LIVE_ADC_COUNTS

    return {
        "raw": data,
        "raw0": raw0,
        "raw1": raw1,
        "raw2": raw2,
        "raw3": raw3,

        "vbus_raw": raw0,
        "ibus_raw": raw1,
        "cc1_raw": raw2,
        "cc2_raw": raw3,

        "vbus_mV": vbus_mV,
        "vbus_V": vbus_mV / 1000.0,
        "ibus_mA": ibus_mA,
        "ibus_A": ibus_mA / 1000.0,
        "ibus_display_A": ibus_mA / 1000.0,
        "cc1_mV": cc1_mV,
        "cc1_V": cc1_mV / 1000.0,
        "cc2_mV": cc2_mV,
        "cc2_V": cc2_mV / 1000.0,

        "power_W": (vbus_mV * ibus_mA) / 1_000_000.0,

        "live_factor": factor,
        "live_val_mV": val_mv,
        "live_vbus_scale_status": "ANALYZER_UTILITY_4_2_0_EXACT",
        "live_current_scale_status": "ANALYZER_UTILITY_4_2_0_EXACT",
        "cc_semantics": "CC1_CC2_CONFIRMED",
    }



@dataclass
class ScopeTimestampUnwrapper:
    """
    Stateful EP83 timestamp unwrapping matching Analyzer Utility 4.2.0.

    The Utility treats the device timestamp as unsigned u32 microseconds,
    ignores 0 and 0xADACABAA, and on wrap adds 0xFFFFFFFF exactly.
    """
    prev_raw: int = 0
    add_factor: int = 0

    def unwrap(self, raw: int) -> Optional[int]:
        raw = int(raw) & 0xFFFFFFFF

        if raw == 0 or raw == SCOPE_TIMESTAMP_SKIP_MAGIC:
            return None

        if raw - self.prev_raw < 0:
            self.add_factor += SCOPE_TIMESTAMP_WRAP_ADD_UTILITY

        unwrapped = raw + self.add_factor
        self.prev_raw = raw
        return unwrapped


@dataclass(frozen=True)
class ScopeSample:
    packet_index: int
    sample_index: int
    timestamp_raw: int
    timestamp_us: int
    vbus_raw: int
    vbus_mV: int
    cc1_raw: int
    cc1_mV: int
    cc2_raw: int
    cc2_mV: int
    ibus_raw: int
    ibus_mA: int

    @property
    def vbus_V(self) -> float:
        return self.vbus_mV / 1000.0

    @property
    def cc1_V(self) -> float:
        return self.cc1_mV / 1000.0

    @property
    def cc2_V(self) -> float:
        return self.cc2_mV / 1000.0

    @property
    def ibus_A(self) -> float:
        return self.ibus_mA / 1000.0

    @property
    def power_W(self) -> float:
        return self.vbus_V * self.ibus_A


@dataclass(frozen=True)
class ScopeTransferDecode:
    """
    Decoded contents of one host EP83 bulk transfer.

    complete_packets:
        Number of complete 64-byte scope packets consumed.
    samples:
        Real samples only. Analyzer Utility's two synthetic graph preamble
        points are intentionally NOT included.
    paddings:
        Bytes 60..63 from each complete packet, preserved verbatim.
    residual:
        Any trailing bytes after the last complete 64-byte packet. Utility
        truncates them; we report them rather than silently losing evidence.
    """
    complete_packets: int
    samples: tuple[ScopeSample, ...]
    paddings: tuple[bytes, ...]
    residual: bytes


@dataclass(frozen=True)
class ScopeGraphPoint:
    """
    Display-only point used to reproduce Analyzer Utility graph initialization.
    This is deliberately separate from ScopeSample so synthetic points can
    never be mistaken for device data.
    """
    timestamp_us: int
    cc1_mV: int
    cc2_mV: int
    ibus_mA: int
    vbus_mV: int


def decode_scope_sample(
    sample: bytes,
    timestamp_state: ScopeTimestampUnwrapper,
    *,
    packet_index: int = 0,
    sample_index: int = 0,
    is_epr: bool = True,
    product_id: int = USB_PID_CY4500_EPR,
) -> Optional[ScopeSample]:
    """
    Decode one confirmed 12-byte EP83 scope sample.

      +0..3   timestamp u32 LE [us]
      +4..5   VBUS raw u16 LE
      +6..7   CC1 raw u16 LE
      +8..9   CC2 raw u16 LE
      +10..11 IBUS raw u16 LE
    """
    sample = bytes(sample)
    if len(sample) != SCOPE_SAMPLE_SIZE:
        raise ValueError(
            f"scope sample must be exactly {SCOPE_SAMPLE_SIZE} bytes, "
            f"got {len(sample)}"
        )

    timestamp_raw = read_u32_le(sample, SCOPE_OFFSET_TIMESTAMP)
    timestamp_us = timestamp_state.unwrap(timestamp_raw)
    if timestamp_us is None:
        return None

    vbus_raw = read_u16_le(sample, SCOPE_OFFSET_VBUS)
    cc1_raw = read_u16_le(sample, SCOPE_OFFSET_CC1)
    cc2_raw = read_u16_le(sample, SCOPE_OFFSET_CC2)
    ibus_raw = read_u16_le(sample, SCOPE_OFFSET_IBUS)

    factor, val_mv = _live_voltage_params(
        is_epr=is_epr,
        product_id=product_id,
    )

    vbus_mV = vbus_raw * val_mv * factor // LIVE_ADC_COUNTS
    cc1_mV = cc1_raw * val_mv // LIVE_ADC_COUNTS
    cc2_mV = cc2_raw * val_mv // LIVE_ADC_COUNTS
    ibus_mA = live_ibus_milliamps(ibus_raw)

    return ScopeSample(
        packet_index=int(packet_index),
        sample_index=int(sample_index),
        timestamp_raw=timestamp_raw,
        timestamp_us=timestamp_us,
        vbus_raw=vbus_raw,
        vbus_mV=vbus_mV,
        cc1_raw=cc1_raw,
        cc1_mV=cc1_mV,
        cc2_raw=cc2_raw,
        cc2_mV=cc2_mV,
        ibus_raw=ibus_raw,
        ibus_mA=ibus_mA,
    )


def decode_scope_transfer(
    data: bytes,
    timestamp_state: Optional[ScopeTimestampUnwrapper] = None,
    *,
    is_epr: bool = True,
    product_id: int = USB_PID_CY4500_EPR,
) -> ScopeTransferDecode:
    """
    Decode complete 64-byte EP83 scope packets from one host bulk transfer.

    Exactly like ScopeCollecter, a non-multiple-of-64 length is truncated to
    the last complete packet for decoding. Unlike the Utility, residual bytes
    are returned to the caller for diagnostics.
    """
    data = bytes(data)
    if timestamp_state is None:
        timestamp_state = ScopeTimestampUnwrapper()

    complete_len = (len(data) // SCOPE_PACKET_SIZE) * SCOPE_PACKET_SIZE
    residual = data[complete_len:]

    samples: list[ScopeSample] = []
    paddings: list[bytes] = []

    packet_count = complete_len // SCOPE_PACKET_SIZE

    for packet_index in range(packet_count):
        base = packet_index * SCOPE_PACKET_SIZE
        packet = data[base : base + SCOPE_PACKET_SIZE]
        paddings.append(packet[SCOPE_PADDING_OFFSET:SCOPE_PACKET_SIZE])

        for sample_index in range(SCOPE_SAMPLES_PER_PACKET):
            start = sample_index * SCOPE_SAMPLE_SIZE
            raw_sample = packet[start : start + SCOPE_SAMPLE_SIZE]
            decoded = decode_scope_sample(
                raw_sample,
                timestamp_state,
                packet_index=packet_index,
                sample_index=sample_index,
                is_epr=is_epr,
                product_id=product_id,
            )
            if decoded is not None:
                samples.append(decoded)

    return ScopeTransferDecode(
        complete_packets=packet_count,
        samples=tuple(samples),
        paddings=tuple(paddings),
        residual=residual,
    )


def scope_graph_preamble(first_sample: ScopeSample) -> tuple[ScopeGraphPoint, ScopeGraphPoint]:
    """
    Reproduce the two synthetic points Analyzer Utility inserts only when its
    graph list is initially empty:

      t-2 us : all values zero
      t-1 us : first sample's values

    The actual first ScopeSample at t is not duplicated here.
    """
    first = first_sample
    return (
        ScopeGraphPoint(
            timestamp_us=first.timestamp_us - 2,
            cc1_mV=0,
            cc2_mV=0,
            ibus_mA=0,
            vbus_mV=0,
        ),
        ScopeGraphPoint(
            timestamp_us=first.timestamp_us - 1,
            cc1_mV=first.cc1_mV,
            cc2_mV=first.cc2_mV,
            ibus_mA=first.ibus_mA,
            vbus_mV=first.vbus_mV,
        ),
    )


# EP81 + EP83 synchronized AVS transition analysis --------------------------

TRANSITION_BASELINE_WINDOW_US = 100_000
TRANSITION_BASELINE_GUARD_US = 5_000
TRANSITION_MOVEMENT_MIN_THRESHOLD_V = 0.050
TRANSITION_MOVEMENT_MAD_MULTIPLIER = 6.0
TRANSITION_MOVEMENT_SUSTAIN_SAMPLES = 5
TRANSITION_TARGET_BAND_FRACTION = 0.01
TRANSITION_SETTLE_HOLD_US = 20_000
TRANSITION_SETTLE_MAX_SAMPLE_GAP_US = 5_000

TRANSITION_PLATEAU_LOOKBACK_US = 150_000
TRANSITION_PLATEAU_MIN_SAMPLES = 50
TRANSITION_RELATIVE_BAND_FRACTION = 0.005
TRANSITION_RELATIVE_SETTLE_HOLD_US = 20_000
TRANSITION_PLATEAU_STABILITY_MIN_SPAN_V = 0.100
TRANSITION_PLATEAU_STABILITY_FRACTION = 0.0025
TRANSITION_PLATEAU_TARGET_GUARD_FRACTION = 0.10


@dataclass(frozen=True)
class SyncPDSample:
    row_index: int
    sno: Optional[int]
    message: str
    start_us: int
    end_us: int
    vbus_V: Optional[float]
    data: bytes


@dataclass(frozen=True)
class SyncScopeSample:
    timestamp_us: int
    vbus_V: float
    ibus_A: Optional[float] = None
    cc1_V: Optional[float] = None
    cc2_V: Optional[float] = None


@dataclass(frozen=True)
class AVSTransitionAnalysis:
    request_row_index: int
    request_sno: Optional[int]
    direction: str
    target_voltage_V: float
    requested_current_A: Optional[float]
    request_start_us: int
    request_end_us: int
    accept_start_us: Optional[int]
    accept_latency_us: Optional[int]
    ps_rdy_start_us: Optional[int]
    ps_rdy_latency_us: Optional[int]
    request_scope_timestamp_us: Optional[int]
    request_scope_vbus_V: Optional[float]
    ps_rdy_scope_timestamp_us: Optional[int]
    ps_rdy_scope_vbus_V: Optional[float]
    baseline_vbus_V: Optional[float]
    baseline_noise_mad_V: Optional[float]
    movement_threshold_V: Optional[float]
    movement_start_us: Optional[int]
    movement_latency_us: Optional[int]
    target_crossing_us: Optional[int]
    target_crossing_latency_us: Optional[int]
    target_band_first_entry_us: Optional[int]
    target_band_first_entry_latency_us: Optional[int]
    settling_us: Optional[int]
    settling_latency_us: Optional[int]
    settling_hold_us: int
    target_band_fraction: float
    average_slew_V_per_s: Optional[float]
    observed_plateau_V: Optional[float]
    observed_plateau_mad_V: Optional[float]
    observed_plateau_sample_count: int
    observed_band_fraction: float
    observed_band_first_entry_us: Optional[int]
    observed_band_first_entry_latency_us: Optional[int]
    observed_settling_us: Optional[int]
    observed_settling_latency_us: Optional[int]
    observed_average_slew_V_per_s: Optional[float]
    flags: tuple[str, ...]


def _median(values: Sequence[float]) -> float:
    ordered = sorted(float(v) for v in values)
    n = len(ordered)
    if not n:
        raise ValueError("median of empty sequence")
    mid = n // 2
    if n & 1:
        return ordered[mid]
    return (ordered[mid - 1] + ordered[mid]) / 2.0


def _mad(values: Sequence[float], center: Optional[float] = None) -> float:
    if not values:
        return 0.0
    if center is None:
        center = _median(values)
    return _median([abs(float(v) - center) for v in values])


def _nearest_scope_sample(
    samples: Sequence[SyncScopeSample],
    timestamp_us: int,
) -> Optional[SyncScopeSample]:
    if not samples:
        return None
    import bisect
    times = [s.timestamp_us for s in samples]
    pos = bisect.bisect_left(times, int(timestamp_us))
    choices = []
    if pos < len(samples):
        choices.append(samples[pos])
    if pos:
        choices.append(samples[pos - 1])
    return min(choices, key=lambda s: abs(s.timestamp_us - timestamp_us))


def _decode_avs_request_from_pd_sample(
    pd: SyncPDSample,
) -> Optional[tuple[float, Optional[float]]]:
    """
    Decode an EPR_REQUEST only when its second 32-bit object identifies an AVS
    APDO. Analyzer capture CSV stores the logical message bytes in Data, i.e.
    RDO first, selected Source PDO second for the tested EPR_REQUEST form.
    """
    if pd.message != "EPR_REQUEST" or len(pd.data) < 8:
        return None

    rdo_raw = int.from_bytes(pd.data[0:4], "little")
    pdo_raw = int.from_bytes(pd.data[4:8], "little")
    pdo = decode_pdo(pdo_raw, position=(rdo_raw >> 28) & 0xF)
    if pdo.get("apdo_name") != "AVS":
        return None

    rdo = decode_rdo(rdo_raw, selected_pdo=pdo)
    target = rdo.get("requested_voltage_V")
    current = rdo.get("operating_current_A")
    if target is None:
        return None
    return float(target), (None if current is None else float(current))


def analyze_avs_transitions(
    pd_samples: Sequence[SyncPDSample],
    scope_samples: Sequence[SyncScopeSample],
    *,
    baseline_window_us: int = TRANSITION_BASELINE_WINDOW_US,
    baseline_guard_us: int = TRANSITION_BASELINE_GUARD_US,
    movement_min_threshold_V: float = TRANSITION_MOVEMENT_MIN_THRESHOLD_V,
    movement_mad_multiplier: float = TRANSITION_MOVEMENT_MAD_MULTIPLIER,
    movement_sustain_samples: int = TRANSITION_MOVEMENT_SUSTAIN_SAMPLES,
    target_band_fraction: float = TRANSITION_TARGET_BAND_FRACTION,
    settle_hold_us: int = TRANSITION_SETTLE_HOLD_US,
    settle_max_sample_gap_us: int = TRANSITION_SETTLE_MAX_SAMPLE_GAP_US,
    plateau_lookback_us: int = TRANSITION_PLATEAU_LOOKBACK_US,
    plateau_min_samples: int = TRANSITION_PLATEAU_MIN_SAMPLES,
    observed_band_fraction: float = TRANSITION_RELATIVE_BAND_FRACTION,
    observed_settle_hold_us: int = TRANSITION_RELATIVE_SETTLE_HOLD_US,
    plateau_stability_min_span_V: float = TRANSITION_PLATEAU_STABILITY_MIN_SPAN_V,
    plateau_stability_fraction: float = TRANSITION_PLATEAU_STABILITY_FRACTION,
    plateau_target_guard_fraction: float = TRANSITION_PLATEAU_TARGET_GUARD_FRACTION,
) -> list[AVSTransitionAnalysis]:
    """
    Correlate EP81 EPR_REQUEST/ACCEPT/PS_RDY messages with EP83 telemetry.

    No host-time offset is estimated or applied. Both streams are compared on
    the raw/unwrapped device microsecond timestamps exactly as captured.

    Matching:
      - For each AVS EPR_REQUEST, walk forward in EP81 order.
      - ACCEPT is the first ACCEPT after the request and before the next
        EPR_REQUEST.
      - PS_RDY is the first PS_RDY after that ACCEPT (or request if ACCEPT is
        absent) and before the next EPR_REQUEST.

    Movement detection:
      - baseline = median EP83 VBUS in [request-baseline_window,
        request-baseline_guard]
      - noise = MAD around baseline
      - threshold = max(min_threshold, MAD * multiplier)
      - movement starts at the first sustained run of N samples beyond that
        threshold in the request direction.

    Absolute settling:
      - target band is ±target_band_fraction of the requested target voltage.
      - settling is the first in-band sample followed by at least settle_hold_us
        of continuous in-band samples, with no inter-sample gap greater than
        settle_max_sample_gap_us.
      - if capture ends before the hold interval completes, settling is not
        declared.

    Observed final-plateau settling:
      - starting at PS_RDY, scan forward for the earliest stable
        plateau_lookback_us EP83 window; this avoids mistaking a later cable
        detach / VBUS collapse for the transition plateau.
      - require at least plateau_min_samples and a bounded VBUS span; among
        plausible candidates near the requested target, choose the stable
        plateau whose own relative band persists the longest.
      - relative band is ±observed_band_fraction of the observed plateau.
      - observed settling is the first sample that remains continuously inside
        that band for observed_settle_hold_us.
      - this does not replace absolute requested-target analysis; both are
        reported side-by-side.
    """
    pd_rows = list(pd_samples)
    scope = sorted(scope_samples, key=lambda s: s.timestamp_us)
    results: list[AVSTransitionAnalysis] = []

    for i, req in enumerate(pd_rows):
        decoded_req = _decode_avs_request_from_pd_sample(req)
        if decoded_req is None:
            continue

        target_v, requested_current = decoded_req

        next_req_index = len(pd_rows)
        for k in range(i + 1, len(pd_rows)):
            if pd_rows[k].message == "EPR_REQUEST":
                next_req_index = k
                break

        accept = None
        ps_rdy = None
        for k in range(i + 1, next_req_index):
            candidate = pd_rows[k]
            if accept is None and candidate.message == "ACCEPT":
                accept = candidate
                continue
            if candidate.message == "PS_RDY" and (
                accept is None or candidate.row_index > accept.row_index
            ):
                ps_rdy = candidate
                break

        nearest_req = _nearest_scope_sample(scope, req.start_us)
        nearest_ps = (
            _nearest_scope_sample(scope, ps_rdy.start_us)
            if ps_rdy is not None else None
        )

        baseline_start = req.start_us - int(baseline_window_us)
        baseline_end = req.start_us - int(baseline_guard_us)
        baseline_samples = [
            s.vbus_V for s in scope
            if baseline_start <= s.timestamp_us <= baseline_end
        ]

        flags: list[str] = []

        if baseline_samples:
            baseline_v = _median(baseline_samples)
            baseline_mad = _mad(baseline_samples, baseline_v)
            movement_threshold = max(
                float(movement_min_threshold_V),
                baseline_mad * float(movement_mad_multiplier),
            )
        else:
            baseline_v = (
                nearest_req.vbus_V if nearest_req is not None else None
            )
            baseline_mad = None
            movement_threshold = (
                float(movement_min_threshold_V)
                if baseline_v is not None else None
            )
            flags.append("baseline_window_unavailable")

        if baseline_v is None:
            direction = "unknown"
        elif target_v > baseline_v:
            direction = "up"
        elif target_v < baseline_v:
            direction = "down"
        else:
            direction = "flat"

        search_end_us = (
            pd_rows[next_req_index].start_us
            if next_req_index < len(pd_rows)
            else (scope[-1].timestamp_us if scope else req.end_us)
        )
        post_scope = [
            s for s in scope
            if req.start_us <= s.timestamp_us < search_end_us
        ]

        movement_start = None
        movement_sample = None
        sustain = max(1, int(movement_sustain_samples))

        if baseline_v is not None and movement_threshold is not None:
            def moved(s: SyncScopeSample) -> bool:
                if direction == "up":
                    return s.vbus_V >= baseline_v + movement_threshold
                if direction == "down":
                    return s.vbus_V <= baseline_v - movement_threshold
                return False

            for n in range(0, max(0, len(post_scope) - sustain + 1)):
                window = post_scope[n:n + sustain]
                if all(moved(s) for s in window):
                    movement_sample = window[0]
                    movement_start = movement_sample.timestamp_us
                    break

        if movement_start is None:
            flags.append("movement_not_detected")

        band_abs = abs(target_v) * float(target_band_fraction)
        band_lo = target_v - band_abs
        band_hi = target_v + band_abs

        crossing_sample = None
        band_first = None
        for s in post_scope:
            if crossing_sample is None:
                if (
                    (direction == "up" and s.vbus_V >= target_v)
                    or (direction == "down" and s.vbus_V <= target_v)
                ):
                    crossing_sample = s
            if band_first is None and band_lo <= s.vbus_V <= band_hi:
                band_first = s
            if crossing_sample is not None and band_first is not None:
                break

        if crossing_sample is None:
            flags.append("target_crossing_not_observed")
        if band_first is None:
            flags.append("target_band_not_reached")

        settling_sample = None
        if band_first is not None:
            start_idx = post_scope.index(band_first)
            for n in range(start_idx, len(post_scope)):
                candidate = post_scope[n]
                if not (band_lo <= candidate.vbus_V <= band_hi):
                    continue
                hold_end = candidate.timestamp_us + int(settle_hold_us)
                if post_scope[-1].timestamp_us < hold_end:
                    flags.append("capture_ended_before_settle_hold")
                    break

                ok = True
                last_t = candidate.timestamp_us
                reached_hold = False
                for s in post_scope[n:]:
                    if s.timestamp_us > hold_end:
                        reached_hold = True
                        break
                    if s.timestamp_us - last_t > int(settle_max_sample_gap_us):
                        ok = False
                        break
                    if not (band_lo <= s.vbus_V <= band_hi):
                        ok = False
                        break
                    last_t = s.timestamp_us

                if ok and reached_hold:
                    settling_sample = candidate
                    break

        if settling_sample is None and band_first is not None:
            if "capture_ended_before_settle_hold" not in flags:
                flags.append("settling_not_observed")

        # Observed final plateau, estimated independently of requested target.
        #
        # Do NOT blindly use the final capture window: the last transition in a
        # session may be followed by cable detach / VBUS collapse. Instead scan
        # forward from PS_RDY (or movement start/request if PS_RDY is absent)
        # for the earliest stable plateau_lookback_us window.
        plateau_scan_start_us = (
            ps_rdy.start_us
            if ps_rdy is not None
            else (
                movement_start
                if movement_start is not None
                else req.start_us
            )
        )

        plateau_samples = []
        observed_plateau_v = None
        observed_plateau_mad = None
        observed_band_first = None
        observed_settling_sample = None
        observed_average_slew = None

        scan_samples = [
            s for s in post_scope
            if s.timestamp_us >= plateau_scan_start_us
        ]

        minimum_count = int(plateau_min_samples)
        window_us = int(plateau_lookback_us)

        # About 1 kS/s: testing every fifth sample keeps this inexpensive while
        # retaining ~5 ms placement resolution. Collect stable candidates and
        # choose the one whose own relative band persists the longest. This
        # rejects short shoulders during a ramp and, together with the target
        # plausibility guard, rejects a later detach-to-zero state.
        best_candidate = None
        best_persist_us = -1

        target_guard_abs = max(
            0.5,
            abs(target_v) * float(plateau_target_guard_fraction),
        )

        for candidate_index in range(0, len(scan_samples), 5):
            candidate = scan_samples[candidate_index]
            window_end_us = candidate.timestamp_us + window_us
            window = [
                s for s in scan_samples[candidate_index:]
                if s.timestamp_us < window_end_us
            ]
            if len(window) < minimum_count:
                continue
            if window[-1].timestamp_us - candidate.timestamp_us < window_us * 0.9:
                continue

            values = [s.vbus_V for s in window]
            median_v = _median(values)
            span_v = max(values) - min(values)
            stable_span_limit = max(
                float(plateau_stability_min_span_V),
                abs(median_v) * float(plateau_stability_fraction),
            )
            if span_v > stable_span_limit:
                continue
            if abs(median_v - target_v) > target_guard_abs:
                continue

            candidate_band_abs = (
                abs(median_v) * float(observed_band_fraction)
            )
            candidate_lo = median_v - candidate_band_abs
            candidate_hi = median_v + candidate_band_abs

            persist_end_us = candidate.timestamp_us
            last_t = candidate.timestamp_us
            persistent_run = []
            for s in scan_samples[candidate_index:]:
                if s.timestamp_us - last_t > int(settle_max_sample_gap_us):
                    break
                if not (candidate_lo <= s.vbus_V <= candidate_hi):
                    break
                persistent_run.append(s)
                persist_end_us = s.timestamp_us
                last_t = s.timestamp_us

            persist_us = persist_end_us - candidate.timestamp_us
            if persist_us > best_persist_us and persistent_run:
                # The initial stable window is only a detector. The plateau
                # value itself is the median of the whole persistent run, which
                # prevents an early shoulder (still inside the relative band)
                # from biasing the reported final plateau.
                run_values = [s.vbus_V for s in persistent_run]
                run_median = _median(run_values)
                best_persist_us = persist_us
                best_candidate = (
                    persistent_run,
                    run_median,
                    _mad(run_values, run_median),
                )

        if best_candidate is not None:
            plateau_samples, observed_plateau_v, observed_plateau_mad = best_candidate

        if observed_plateau_v is not None:
            observed_band_abs = (
                abs(observed_plateau_v) * float(observed_band_fraction)
            )
            observed_band_lo = observed_plateau_v - observed_band_abs
            observed_band_hi = observed_plateau_v + observed_band_abs

            for s in post_scope:
                if observed_band_lo <= s.vbus_V <= observed_band_hi:
                    observed_band_first = s
                    break

            if observed_band_first is not None:
                start_idx = post_scope.index(observed_band_first)
                for n in range(start_idx, len(post_scope)):
                    candidate = post_scope[n]
                    if not (
                        observed_band_lo <= candidate.vbus_V <= observed_band_hi
                    ):
                        continue
                    hold_end = candidate.timestamp_us + int(observed_settle_hold_us)
                    if post_scope[-1].timestamp_us < hold_end:
                        break

                    ok = True
                    reached_hold = False
                    last_t = candidate.timestamp_us
                    for s in post_scope[n:]:
                        if s.timestamp_us > hold_end:
                            reached_hold = True
                            break
                        if (
                            s.timestamp_us - last_t
                            > int(settle_max_sample_gap_us)
                        ):
                            ok = False
                            break
                        if not (
                            observed_band_lo <= s.vbus_V <= observed_band_hi
                        ):
                            ok = False
                            break
                        last_t = s.timestamp_us

                    if ok and reached_hold:
                        observed_settling_sample = candidate
                        break

            if (
                movement_sample is not None
                and observed_band_first is not None
                and observed_band_first.timestamp_us > movement_sample.timestamp_us
            ):
                observed_average_slew = (
                    (observed_band_first.vbus_V - movement_sample.vbus_V)
                    / (
                        (
                            observed_band_first.timestamp_us
                            - movement_sample.timestamp_us
                        )
                        / 1e6
                    )
                )
        else:
            flags.append("observed_plateau_not_found")

        if observed_plateau_v is not None and observed_band_first is None:
            flags.append("observed_band_not_reached")
        elif observed_band_first is not None and observed_settling_sample is None:
            flags.append("observed_settling_not_observed")

        average_slew = None
        if (
            movement_sample is not None
            and band_first is not None
            and band_first.timestamp_us > movement_sample.timestamp_us
        ):
            average_slew = (
                (band_first.vbus_V - movement_sample.vbus_V)
                / ((band_first.timestamp_us - movement_sample.timestamp_us) / 1e6)
            )

        results.append(
            AVSTransitionAnalysis(
                request_row_index=req.row_index,
                request_sno=req.sno,
                direction=direction,
                target_voltage_V=target_v,
                requested_current_A=requested_current,
                request_start_us=req.start_us,
                request_end_us=req.end_us,
                accept_start_us=(None if accept is None else accept.start_us),
                accept_latency_us=(
                    None if accept is None
                    else accept.start_us - req.start_us
                ),
                ps_rdy_start_us=(None if ps_rdy is None else ps_rdy.start_us),
                ps_rdy_latency_us=(
                    None if ps_rdy is None
                    else ps_rdy.start_us - req.start_us
                ),
                request_scope_timestamp_us=(
                    None if nearest_req is None else nearest_req.timestamp_us
                ),
                request_scope_vbus_V=(
                    None if nearest_req is None else nearest_req.vbus_V
                ),
                ps_rdy_scope_timestamp_us=(
                    None if nearest_ps is None else nearest_ps.timestamp_us
                ),
                ps_rdy_scope_vbus_V=(
                    None if nearest_ps is None else nearest_ps.vbus_V
                ),
                baseline_vbus_V=baseline_v,
                baseline_noise_mad_V=baseline_mad,
                movement_threshold_V=movement_threshold,
                movement_start_us=movement_start,
                movement_latency_us=(
                    None if movement_start is None
                    else movement_start - req.start_us
                ),
                target_crossing_us=(
                    None if crossing_sample is None
                    else crossing_sample.timestamp_us
                ),
                target_crossing_latency_us=(
                    None if crossing_sample is None
                    else crossing_sample.timestamp_us - req.start_us
                ),
                target_band_first_entry_us=(
                    None if band_first is None
                    else band_first.timestamp_us
                ),
                target_band_first_entry_latency_us=(
                    None if band_first is None
                    else band_first.timestamp_us - req.start_us
                ),
                settling_us=(
                    None if settling_sample is None
                    else settling_sample.timestamp_us
                ),
                settling_latency_us=(
                    None if settling_sample is None
                    else settling_sample.timestamp_us - req.start_us
                ),
                settling_hold_us=int(settle_hold_us),
                target_band_fraction=float(target_band_fraction),
                average_slew_V_per_s=average_slew,
                observed_plateau_V=observed_plateau_v,
                observed_plateau_mad_V=observed_plateau_mad,
                observed_plateau_sample_count=len(plateau_samples),
                observed_band_fraction=float(observed_band_fraction),
                observed_band_first_entry_us=(
                    None if observed_band_first is None
                    else observed_band_first.timestamp_us
                ),
                observed_band_first_entry_latency_us=(
                    None if observed_band_first is None
                    else observed_band_first.timestamp_us - req.start_us
                ),
                observed_settling_us=(
                    None if observed_settling_sample is None
                    else observed_settling_sample.timestamp_us
                ),
                observed_settling_latency_us=(
                    None if observed_settling_sample is None
                    else observed_settling_sample.timestamp_us - req.start_us
                ),
                observed_average_slew_V_per_s=observed_average_slew,
                flags=tuple(dict.fromkeys(flags)),
            )
        )

    return results

def vbus_epr_volts(raw: int) -> float:
    """
    Convert CY4500-EPR VBUS raw count to volts.

    Analyzer Utility's confirmed arithmetic produces a millivolt-scale value:
        raw * 4048 * 12 / 4096

    Direct capture empirically matches ~5.04..5.10 V at raw 425..430 and
    ~0.75 V at raw 63, so divide by 1000 for volts.
    """
    raw = int(raw)
    if raw < 0:
        raise ValueError("raw must be >= 0")
    return (
        raw
        * VBUS_EPR_MULTIPLIER
        * VBUS_EPR_GAIN
        / VBUS_EPR_DIVISOR
        / 1000.0
    )


def capture_record_logical_message_bytes(record: bytes) -> bytes:
    """
    Return only the valid message bytes carried by one 64-byte record.

    IMPORTANT: the unused tail of record[20:64] is not guaranteed to be
    zeroed; direct capture proved that stale bytes can remain there.
    For PD records, Number of Data Objects determines the valid physical
    message-area length for that record: NDO * 4 bytes.

    For Extended Messages this returns the physical chunk bytes present in
    THIS record (including the 2-byte Extended Header), not a reassembled
    multi-chunk Extended Message.
    """
    if len(record) != CAPTURE_RECORD_SIZE:
        raise ValueError(
            f"record must be exactly {CAPTURE_RECORD_SIZE} bytes"
        )

    word = read_u32_le(record, CAPTURE_OFFSET_PACKET_WORD)
    fields = decode_packet_word(word)

    if fields["PKT_TYPE"] != 0:
        return b""

    logical_len = fields["OBJ_COUNT"] * DATA_OBJECT_SIZE
    return bytes(
        record[
            CAPTURE_OFFSET_MESSAGE:
            CAPTURE_OFFSET_MESSAGE + logical_len
        ]
    )


def u32_elapsed(end_value: int, start_value: int) -> int:
    """Unsigned 32-bit wrap-safe counter difference."""
    return (int(end_value) - int(start_value)) & 0xFFFFFFFF


def _trigger_class(value) -> int:
    if isinstance(value, str):
        key = value.upper()
        if key not in TRIGGER_MSG_CLASS:
            raise ValueError(f"unknown trigger message class: {value!r}")
        return TRIGGER_MSG_CLASS[key]
    value = int(value)
    if value not in TRIGGER_MSG_CLASS_BY_VALUE:
        raise ValueError("trigger msg_class must be 0..2")
    return value


def _trigger_sop(value) -> int:
    if isinstance(value, str):
        key = value.upper()
        if key not in TRIGGER_SOP_TYPE:
            raise ValueError(f"unknown trigger SOP: {value!r}")
        return TRIGGER_SOP_TYPE[key]
    value = int(value)
    if value not in TRIGGER_SOP_TYPE_BY_VALUE:
        raise ValueError("trigger SOP must be 0..6")
    return value


def _trigger_msg_type(class_value: int, value) -> int:
    cls = TRIGGER_MSG_CLASS_BY_VALUE[class_value]
    table = MESSAGE_TYPES_BY_CLASS[cls]
    if isinstance(value, str):
        key = value.upper()
        try:
            return table.index(key)
        except ValueError as exc:
            raise ValueError(f"{value!r} is not a {cls} message") from exc
    value = int(value)
    if not 0 <= value <= 31:
        raise ValueError("trigger msg_type must be 0..31")
    return value


def build_trigger_packet(
    *,
    start_sno: Optional[int] = None,
    end_sno: Optional[int] = None,
    sop=None,
    msg_class=None,
    msg_type=None,
    obj_count: Optional[int] = None,
    msg_id: Optional[int] = None,
) -> bytes:
    """Build Analyzer Utility's exact 64-byte CMD_TRIGGER packet."""
    p = bytearray(TRIGGER_PACKET_SIZE)
    p[TRIGGER_OFFSET_CMD] = CMD_TRIGGER

    if start_sno is not None:
        p[TRIGGER_OFFSET_START_SNO_ENABLE] = 1
        p[TRIGGER_OFFSET_START_SNO:TRIGGER_OFFSET_START_SNO + 4] = write_u32_le(start_sno)

    if end_sno is not None:
        p[TRIGGER_OFFSET_END_SNO_ENABLE] = 1
        p[TRIGGER_OFFSET_END_SNO:TRIGGER_OFFSET_END_SNO + 4] = write_u32_le(end_sno)

    if sop is not None:
        p[TRIGGER_OFFSET_SOP_ENABLE] = 1
        p[TRIGGER_OFFSET_SOP] = _trigger_sop(sop)

    cls_value = None
    if msg_class is not None:
        cls_value = _trigger_class(msg_class)

    if msg_type is not None:
        if cls_value is None:
            raise ValueError("msg_type requires msg_class")
        p[TRIGGER_OFFSET_MSG_TYPE_ENABLE] = 1
        p[TRIGGER_OFFSET_MSG_TYPE] = _trigger_msg_type(cls_value, msg_type)
        p[TRIGGER_OFFSET_MSG_CLASS] = cls_value
    elif cls_value is not None:
        raise ValueError("msg_class alone is not an independent trigger condition")

    if obj_count is not None:
        n = int(obj_count)
        if not 0 <= n <= 7:
            raise ValueError("obj_count must be 0..7")
        p[TRIGGER_OFFSET_OBJ_COUNT_ENABLE] = 1
        p[TRIGGER_OFFSET_OBJ_COUNT] = n

    if msg_id is not None:
        n = int(msg_id)
        if not 0 <= n <= 7:
            raise ValueError("msg_id must be 0..7")
        p[TRIGGER_OFFSET_MSG_ID_ENABLE] = 1
        p[TRIGGER_OFFSET_MSG_ID] = n

    return bytes(p)


def build_clear_trigger_packet() -> bytes:
    """CMD_TRIGGER with enable bytes 4..9 all zero: physically verified clear."""
    p = bytearray(TRIGGER_PACKET_SIZE)
    p[TRIGGER_OFFSET_CMD] = CMD_TRIGGER
    return bytes(p)


def _termination(value) -> int:
    if isinstance(value, str):
        key = value.upper()
        if key not in CC_TERMINATION:
            raise ValueError(f"unknown CC termination: {value!r}")
        return CC_TERMINATION[key]
    value = int(value)
    if value not in CC_TERMINATION_BY_VALUE:
        raise ValueError("termination must be 1, 2, 3, or 4")
    return value


def build_termination_packet(cc1="NONE", cc2="NONE") -> bytes:
    p = bytearray(TERMINATION_PACKET_SIZE)
    p[TERMINATION_OFFSET_CMD] = CMD_TERMINATION
    p[TERMINATION_OFFSET_CC1] = _termination(cc1)
    p[TERMINATION_OFFSET_CC2] = _termination(cc2)
    return bytes(p)


def decode_pdo(pdo: int, *, position: Optional[int] = None) -> dict[str, object]:
    """Decode one 32-bit Source PDO into conservative, human-readable fields."""
    pdo = int(pdo) & 0xFFFFFFFF
    supply_type = (pdo >> 30) & 0x03
    kind = PDO_SUPPLY_TYPES.get(supply_type, f"UNKNOWN_{supply_type}")

    out: dict[str, object] = {
        "raw": pdo,
        "raw_hex": f"0x{pdo:08X}",
        "position": position,
        "supply_type": supply_type,
        "kind": kind,
    }

    if supply_type == 0:  # Fixed Supply PDO
        voltage_raw = (pdo >> 10) & 0x03FF
        current_raw = pdo & 0x03FF
        out.update(
            voltage_V=voltage_raw * 0.05,
            max_current_A=current_raw * 0.01,
            max_power_W=voltage_raw * 0.05 * current_raw * 0.01,
            voltage_raw_50mV=voltage_raw,
            current_raw_10mA=current_raw,
        )

    elif supply_type == 1:  # Battery Supply PDO
        max_voltage_raw = (pdo >> 20) & 0x03FF
        min_voltage_raw = (pdo >> 10) & 0x03FF
        power_raw = pdo & 0x03FF
        out.update(
            min_voltage_V=min_voltage_raw * 0.05,
            max_voltage_V=max_voltage_raw * 0.05,
            max_power_W=power_raw * 0.25,
            min_voltage_raw_50mV=min_voltage_raw,
            max_voltage_raw_50mV=max_voltage_raw,
            power_raw_250mW=power_raw,
        )

    elif supply_type == 2:  # Variable Supply PDO
        max_voltage_raw = (pdo >> 20) & 0x03FF
        min_voltage_raw = (pdo >> 10) & 0x03FF
        current_raw = pdo & 0x03FF
        out.update(
            min_voltage_V=min_voltage_raw * 0.05,
            max_voltage_V=max_voltage_raw * 0.05,
            max_current_A=current_raw * 0.01,
            min_voltage_raw_50mV=min_voltage_raw,
            max_voltage_raw_50mV=max_voltage_raw,
            current_raw_10mA=current_raw,
        )

    else:  # Augmented PDO
        apdo_type = (pdo >> 28) & 0x03
        apdo_name = APDO_TYPES.get(apdo_type, f"UNKNOWN_{apdo_type}")
        out.update(
            apdo_type=apdo_type,
            apdo_name=apdo_name,
        )

        if apdo_type == 0:  # PPS APDO
            max_voltage_raw = (pdo >> 17) & 0x00FF
            min_voltage_raw = (pdo >> 8) & 0x00FF
            current_raw = pdo & 0x007F
            out.update(
                min_voltage_V=min_voltage_raw * 0.1,
                max_voltage_V=max_voltage_raw * 0.1,
                max_current_A=current_raw * 0.05,
                min_voltage_raw_100mV=min_voltage_raw,
                max_voltage_raw_100mV=max_voltage_raw,
                current_raw_50mA=current_raw,
            )

        elif apdo_type == 1:  # EPR AVS APDO
            max_voltage_raw = (pdo >> 17) & 0x01FF
            min_voltage_raw = (pdo >> 8) & 0x01FF
            pdp_raw = pdo & 0x00FF
            out.update(
                min_voltage_V=min_voltage_raw * 0.1,
                max_voltage_V=max_voltage_raw * 0.1,
                pdp_W=pdp_raw,
                min_voltage_raw_100mV=min_voltage_raw,
                max_voltage_raw_100mV=max_voltage_raw,
                pdp_raw_1W=pdp_raw,
            )

        elif apdo_type == 2:
            # Do not guess the remaining SPR AVS field layout yet.
            out["field_decode_status"] = "RAW_ONLY"

    return out


def format_pdo(pdo: dict[str, object]) -> str:
    """Compact human-readable PDO description."""
    pos = pdo.get("position")
    prefix = f"PDO{pos} " if pos is not None else ""

    kind = pdo.get("kind")
    if kind == "FIXED":
        return (
            f"{prefix}FIXED {pdo['voltage_V']:.2f}V "
            f"{pdo['max_current_A']:.2f}A"
        )
    if kind == "BATTERY":
        return (
            f"{prefix}BATTERY {pdo['min_voltage_V']:.2f}-"
            f"{pdo['max_voltage_V']:.2f}V "
            f"{pdo['max_power_W']:.2f}W"
        )
    if kind == "VARIABLE":
        return (
            f"{prefix}VARIABLE {pdo['min_voltage_V']:.2f}-"
            f"{pdo['max_voltage_V']:.2f}V "
            f"{pdo['max_current_A']:.2f}A"
        )
    if kind == "AUGMENTED":
        apdo = pdo.get("apdo_name")
        if apdo == "PPS":
            return (
                f"{prefix}PPS {pdo['min_voltage_V']:.2f}-"
                f"{pdo['max_voltage_V']:.2f}V "
                f"{pdo['max_current_A']:.2f}A"
            )
        if apdo == "AVS":
            return (
                f"{prefix}AVS {pdo['min_voltage_V']:.1f}-"
                f"{pdo['max_voltage_V']:.1f}V "
                f"PDP={pdo['pdp_W']}W"
            )
        return f"{prefix}{apdo} {pdo['raw_hex']} (raw fields)"
    return f"{prefix}{pdo.get('raw_hex', '')}"


def decode_source_capabilities_payload(payload: bytes) -> list[dict[str, object]]:
    """Decode a normal SOURCE_CAPABILITIES Data Message payload."""
    payload = bytes(payload)
    if len(payload) % 4:
        raise ValueError("Source Capabilities payload must be 32-bit aligned")

    return [
        decode_pdo(
            read_u32_le(payload, offset),
            position=offset // 4 + 1,
        )
        for offset in range(0, len(payload), 4)
    ]


def decode_epr_source_capabilities_payload(payload: bytes) -> dict[str, object]:
    """
    Decode reassembled EPR_SOURCE_CAPABILITIES Extended payload.

    The directly observed message is 44 bytes / 11 PDO slots:
      slots 1..7  = SPR PDO slots
      slots 8..11 = EPR PDO slots

    Zero-valued unused slots are preserved and explicitly marked.
    """
    payload = bytes(payload)
    if len(payload) % 4:
        raise ValueError("EPR Source Capabilities payload must be 32-bit aligned")

    slots = []
    for offset in range(0, len(payload), 4):
        position = offset // 4 + 1
        raw = read_u32_le(payload, offset)
        domain = "SPR" if position <= 7 else "EPR"
        if raw == 0:
            slots.append(
                {
                    "position": position,
                    "domain": domain,
                    "raw": 0,
                    "raw_hex": "0x00000000",
                    "unused": True,
                }
            )
        else:
            item = decode_pdo(raw, position=position)
            item["domain"] = domain
            item["unused"] = False
            slots.append(item)

    return {
        "size": len(payload),
        "slot_count": len(slots),
        "slots": slots,
        "active_pdos": [item for item in slots if not item.get("unused")],
    }


def _decode_rdo_flags(rdo: int) -> dict[str, object]:
    rdo = int(rdo) & 0xFFFFFFFF
    return {
        "raw": rdo,
        "raw_hex": f"0x{rdo:08X}",
        "object_position": (rdo >> 28) & 0x0F,
        "giveback": (rdo >> 27) & 1,
        "capability_mismatch": (rdo >> 26) & 1,
        "usb_communications_capable": (rdo >> 25) & 1,
        "no_usb_suspend": (rdo >> 24) & 1,
    }


def decode_rdo(
    rdo: int,
    *,
    selected_pdo: Optional[dict[str, object] | int] = None,
) -> dict[str, object]:
    """
    Decode an RDO using the selected Source PDO when known.

    Without the selected PDO, only common flags and raw request fields are
    returned; this avoids applying the wrong Fixed/PPS/AVS units.
    """
    rdo = int(rdo) & 0xFFFFFFFF
    out = _decode_rdo_flags(rdo)

    if isinstance(selected_pdo, int):
        selected_pdo = decode_pdo(
            selected_pdo,
            position=out["object_position"],
        )

    if selected_pdo is None:
        out.update(
            decode_mode="GENERIC",
            raw_field_20_9=(rdo >> 9) & 0x0FFF,
            raw_field_19_10=(rdo >> 10) & 0x03FF,
            raw_field_9_0=rdo & 0x03FF,
            raw_field_6_0=rdo & 0x007F,
        )
        return out

    out["selected_pdo"] = selected_pdo
    kind = selected_pdo.get("kind")
    out["decode_mode"] = kind

    if kind in ("FIXED", "VARIABLE"):
        op_raw = (rdo >> 10) & 0x03FF
        max_raw = rdo & 0x03FF
        out.update(
            operating_current_A=op_raw * 0.01,
            max_operating_current_A=max_raw * 0.01,
            operating_current_raw_10mA=op_raw,
            max_current_raw_10mA=max_raw,
        )

    elif kind == "BATTERY":
        op_raw = (rdo >> 10) & 0x03FF
        max_raw = rdo & 0x03FF
        out.update(
            operating_power_W=op_raw * 0.25,
            max_operating_power_W=max_raw * 0.25,
            operating_power_raw_250mW=op_raw,
            max_power_raw_250mW=max_raw,
        )

    elif kind == "AUGMENTED":
        apdo_name = selected_pdo.get("apdo_name")

        if apdo_name == "PPS":
            voltage_raw = (rdo >> 9) & 0x0FFF
            current_raw = rdo & 0x007F
            out.update(
                decode_mode="PPS",
                requested_voltage_V=voltage_raw * 0.02,
                operating_current_A=current_raw * 0.05,
                voltage_raw_20mV=voltage_raw,
                current_raw_50mA=current_raw,
            )

        elif apdo_name == "AVS":
            # Observed EPR AVS request 0xB044B064 paired with 0xD3C096F0
            # decodes to 15.000 V / 5.00 A using 25 mV / 50 mA units.
            voltage_raw = (rdo >> 9) & 0x0FFF
            current_raw = rdo & 0x007F
            out.update(
                decode_mode="AVS",
                requested_voltage_V=voltage_raw * 0.025,
                operating_current_A=current_raw * 0.05,
                voltage_raw_25mV=voltage_raw,
                current_raw_50mA=current_raw,
            )

        elif apdo_name == "SPR_AVS":
            # The user's direct capture REQUEST 0x5042D03C selects the
            # subtype-2 SPR_AVS APDO and yields 9.000 V / 3.00 A with the
            # same 25 mV / 50 mA RDO units used by AVS.
            voltage_raw = (rdo >> 9) & 0x0FFF
            current_raw = rdo & 0x007F
            out.update(
                decode_mode="SPR_AVS",
                requested_voltage_V=voltage_raw * 0.025,
                operating_current_A=current_raw * 0.05,
                voltage_raw_25mV=voltage_raw,
                current_raw_50mA=current_raw,
            )

        else:
            out.update(
                decode_mode=str(apdo_name or "AUGMENTED"),
                field_decode_status="RAW_ONLY",
                raw_field_20_9=(rdo >> 9) & 0x0FFF,
                raw_field_6_0=rdo & 0x007F,
            )

    return out


def format_rdo(rdo: dict[str, object]) -> str:
    """Compact human-readable Request description."""
    pos = rdo.get("object_position")
    mode = rdo.get("decode_mode")

    if mode in ("FIXED", "VARIABLE"):
        selected = rdo.get("selected_pdo") or {}
        if mode == "FIXED" and "voltage_V" in selected:
            return (
                f"PDO{pos} FIXED {selected['voltage_V']:.2f}V "
                f"{rdo['operating_current_A']:.2f}A "
                f"(max {rdo['max_operating_current_A']:.2f}A)"
            )
        return (
            f"PDO{pos} {mode} "
            f"{rdo['operating_current_A']:.2f}A "
            f"(max {rdo['max_operating_current_A']:.2f}A)"
        )
    if mode == "BATTERY":
        return (
            f"PDO{pos} BATTERY "
            f"{rdo['operating_power_W']:.2f}W "
            f"(max {rdo['max_operating_power_W']:.2f}W)"
        )
    if mode in ("PPS", "AVS", "SPR_AVS"):
        return (
            f"PDO{pos} {mode} "
            f"{rdo['requested_voltage_V']:.3f}V "
            f"{rdo['operating_current_A']:.2f}A"
        )
    return f"PDO{pos} {mode or 'GENERIC'} {rdo['raw_hex']}"


def decode_request_payload(
    payload: bytes,
    *,
    selected_pdo: Optional[dict[str, object] | int] = None,
) -> dict[str, object]:
    payload = bytes(payload)
    if len(payload) < 4:
        raise ValueError("REQUEST payload must contain one RDO")
    rdo_raw = read_u32_le(payload, 0)
    return decode_rdo(rdo_raw, selected_pdo=selected_pdo)


def decode_epr_request_payload(payload: bytes) -> dict[str, object]:
    """
    Decode observed 8-byte EPR_REQUEST payload.

    Direct captures show:
      DWORD0 = RDO
      DWORD1 = selected Source PDO value carried with the EPR request

    The second DWORD makes the RDO interpretation self-contained.
    """
    payload = bytes(payload)
    if len(payload) < 8:
        raise ValueError("EPR_REQUEST payload must contain two data objects")

    rdo_raw = read_u32_le(payload, 0)
    selected_raw = read_u32_le(payload, 4)
    position = (rdo_raw >> 28) & 0x0F
    selected = decode_pdo(selected_raw, position=position)
    rdo = decode_rdo(rdo_raw, selected_pdo=selected)

    return {
        "rdo": rdo,
        "selected_pdo": selected,
        "summary": format_rdo(rdo),
    }


def decode_extended_control_message(
    logical_message_bytes: bytes,
) -> Optional[dict[str, object]]:
    """Decode EXTENDED_CONTROL_MSG subtype when enough bytes are present."""
    data = bytes(logical_message_bytes)
    if len(data) < 4:
        return None

    ext_header = decode_extended_header(read_u16_le(data, 0))
    control_type = read_u16_le(data, 2)
    name = EXTENDED_CONTROL_TYPES.get(
        control_type,
        f"EXTENDED_CONTROL_TYPE_{control_type}",
    )
    return {
        "type": control_type,
        "name": name,
        "extended_header": ext_header,
        "payload": data[2:],
    }


def decode_capture_record(record: bytes) -> dict[str, object]:
    """Decode one fixed 64-byte record; Extended multi-chunk reassembly is external."""
    if len(record) != CAPTURE_RECORD_SIZE:
        raise ValueError(f"record must be exactly {CAPTURE_RECORD_SIZE} bytes")

    word = read_u32_le(record, CAPTURE_OFFSET_PACKET_WORD)
    fields = decode_packet_word(word)
    logical = capture_record_logical_message_bytes(record)

    out: dict[str, object] = {
        "sno": read_u32_le(record, CAPTURE_OFFSET_SNO),
        "vbus_raw": read_u32_le(record, CAPTURE_OFFSET_VBUS_RAW),
        "vbus_V": vbus_epr_volts(read_u32_le(record, CAPTURE_OFFSET_VBUS_RAW)),
        "start_time": read_u32_le(record, CAPTURE_OFFSET_START_TIME),
        "end_time": read_u32_le(record, CAPTURE_OFFSET_END_TIME),
        "timestamp_unit": TIMESTAMP_UNIT,
        "packet_word": word,
        "pd_header": word & 0xFFFF,
        "fields": fields,
        "pkt_type_name": PKT_TYPE.get(
            fields["PKT_TYPE"],
            f"UNKNOWN_{fields['PKT_TYPE']}",
        ),
        "sop_name": CAPTURE_SOP_TYPE.get(
            fields["SOP_TYPE"],
            f"UNKNOWN_{fields['SOP_TYPE']}",
        ),
        "spec_rev_name": SPEC_REV.get(
            fields["SPEC_REV"],
            f"UNKNOWN_{fields['SPEC_REV']}",
        ),
        "message_area": record[CAPTURE_OFFSET_MESSAGE:],
        "logical_message_bytes": logical,
        "effective_message_name": None,
        "semantic": None,
    }

    if fields["PKT_TYPE"] == 0:
        cls = get_message_class_from_fields(
            extended=fields["EXTENDED"],
            obj_count=fields["OBJ_COUNT"],
        )
        base_name = get_message_name(
            cls,
            fields["MSG_TYPE"],
            f"UNKNOWN_{fields['MSG_TYPE']}",
        )
        out["message_class"] = cls
        out["message_name"] = base_name
        out["effective_message_name"] = base_name
    else:
        out["message_class"] = None
        out["message_name"] = None
        out["effective_message_name"] = out["pkt_type_name"]

    out["extended_header"] = (
        decode_extended_header(read_u16_le(record, CAPTURE_OFFSET_MESSAGE))
        if fields["EXTENDED"] else None
    )

    if fields["PKT_TYPE"] != 0:
        return out

    name = out["message_name"]

    if name == "SOURCE_CAPABILITIES":
        pdos = decode_source_capabilities_payload(logical)
        out["semantic"] = {
            "kind": "SOURCE_CAPABILITIES",
            "pdos": pdos,
        }

    elif name == "REQUEST":
        request = decode_request_payload(logical)
        out["semantic"] = {
            "kind": "REQUEST",
            "request": request,
        }

    elif name == "EPR_REQUEST":
        request = decode_epr_request_payload(logical)
        out["semantic"] = {
            "kind": "EPR_REQUEST",
            **request,
        }

    elif name == "EXTENDED_CONTROL_MSG":
        detail = decode_extended_control_message(logical)
        if detail is not None:
            out["semantic"] = {
                "kind": "EXTENDED_CONTROL",
                **detail,
            }
            out["effective_message_name"] = detail["name"]

    elif name == "EPR_SOURCE_CAPABILITIES":
        ext = out["extended_header"]
        out["semantic"] = {
            "kind": "EPR_SOURCE_CAPABILITIES_CHUNK",
            "request_chunk": ext["request_chunk"],
            "chunk_no": ext["chunk_no"],
            "data_size": ext["data_size"],
            "payload_fragment": logical[2:] if len(logical) >= 2 else b"",
        }

    return out


@dataclass(frozen=True)
class CaptureRecordHeader:
    sno: int
    vbus_raw: int
    start_time: int
    end_time: int
    packet_word: int

    @classmethod
    def from_record(cls, record: bytes) -> "CaptureRecordHeader":
        if len(record) != CAPTURE_RECORD_SIZE:
            raise ValueError(f"record must be exactly {CAPTURE_RECORD_SIZE} bytes")
        return cls(
            sno=read_u32_le(record, CAPTURE_OFFSET_SNO),
            vbus_raw=read_u32_le(record, CAPTURE_OFFSET_VBUS_RAW),
            start_time=read_u32_le(record, CAPTURE_OFFSET_START_TIME),
            end_time=read_u32_le(record, CAPTURE_OFFSET_END_TIME),
            packet_word=read_u32_le(record, CAPTURE_OFFSET_PACKET_WORD),
        )
